steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/ai-math-tutor-prod/web-repo/tutorai-web:v1', '-f', 'infra/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast1-docker.pkg.dev/ai-math-tutor-prod/web-repo/tutorai-web:v1']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
    'gcloud', 'run', 'deploy', 'tutorai-web',
    '--image=asia-southeast1-docker.pkg.dev/ai-math-tutor-prod/web-repo/tutorai-web:v1',
    '--region=asia-southeast1',
    '--allow-unauthenticated',
    '--port=8080',
    '--set-env-vars=NODE_ENV=production,NEXT_PUBLIC_ENV=staging',
    '--set-env-vars=FIREBASE_PROJECT_ID=ai-math-tutor-prod,NEXT_PUBLIC_FIREBASE_PROJECT_ID=ai-math-tutor-prod',
    '--set-env-vars=NEXT_PUBLIC_FIREBASE_API_KEY=dummy-key-for-runtime',
    '--set-env-vars=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=ai-math-tutor-prod.firebaseapp.com',
    '--set-env-vars=NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=ai-math-tutor-prod.appspot.com',
    '--set-env-vars=NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=739150684593',
    '--set-env-vars=NEXT_PUBLIC_FIREBASE_APP_ID=dummy-app-id-for-runtime',
    '--set-env-vars=FIREBASE_CLIENT_EMAIL=firebase-admin@ai-math-tutor-prod.iam.gserviceaccount.com',
    '--set-env-vars=GOOGLE_CLOUD_PROJECT=ai-math-tutor-prod,GOOGLE_CLOUD_REGION=asia-southeast1',
    '--set-env-vars=SANITY_PROJECT_ID=nq8wt9av,SANITY_DATASET=production',
    '--set-secrets=FIREBASE_PRIVATE_KEY=FIREBASE_PRIVATE_KEY:latest,GOOGLE_APPLICATION_CREDENTIALS=VERTEX_AI_SERVICE_KEY:latest,SANITY_API_TOKEN=SANITY_API_TOKEN:latest'
  ]
timeout: 1200s